# Generated by Django 5.1.1 on 2024-10-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destinationdata',
            name='id',
        ),
        migrations.AlterField(
            model_name='destinationdata',
            name='place_name',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
    ]
