# Generated by Django 5.1.1 on 2024-10-06 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationdata',
            old_name='place_name',
            new_name='dest_name',
        ),
    ]
