# Generated by Django 5.1.1 on 2024-10-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_rename_place_name_destinationdata_dest_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destinationdata',
            old_name='dest_name',
            new_name='place_name',
        ),
    ]
